### ISSUE TITLE
Deletes style tag iteratively

### ISSUE THREAD

**Issue by galacticgibbon** [meteorlxy/eslint-plugin-prettier-vue#1]
<img width="165" alt="Screenshot 2019-08-03 at 15 14 13" src="https://user-images.githubusercontent.com/9589803/62409447-8b4fdc00-b601-11e9-9e54-66e9225e94a5.png">

after --fix

<img width="159" alt="Screenshot 2019-08-03 at 15 14 18" src="https://user-images.githubusercontent.com/9589803/62409448-8e4acc80-b601-11e9-8c5c-67feddfb427a.png">

**Comment by meteorlxy** [comment]
Thanks for reporting. Empty tag is an edge case that I didn't notice

**Comment by meteorlxy** [comment]
Fixed in `v0.1.2`.

Currently we process `<script>` and `<style>` blocks differently from custom blocks, which caused this bug.

Processing them in a same way could be a better way.
