### ISSUE TITLE
prettier 'vueIndentScriptAndStyle=true' doesnt work 

### ISSUE THREAD

**Issue by zta7** [meteorlxy/eslint-plugin-prettier-vue#12]

**Comment by meteorlxy** [comment]
Yes, because this plugin does not process the whole `.vue` file. It's a known limitation

**Comment by meteorlxy** [comment]
It should be listed in the docs

**Comment by zta7** [comment]
it's possible to resolve ? or a limitation ? it's the only short for me to use this plugin. ~(i dont like prettier format everything without enough options to choose~)

**Comment by meteorlxy** [comment]
It a limitation of our current workflow:

Split `.vue` file to several blocks -> Put these blocks to prettier independently.

BTW, I think the official style guide of Vuejs does not encourage indent in script and style block of `.vue` file

**Comment by meteorlxy** [comment]
It's possible to resolve, but we need to change the behavior of processing `<script>` and `<style>` blocks 🤔

**Comment by meteorlxy** [comment]
Fixed in v2.1.1

**Comment by holyrong** [comment]
@meteorlxy my vs code doesn't work , too.
prettier:2.3.2

prettier.config.js like this:
![image](https://user-images.githubusercontent.com/8318475/130945697-e505cb98-0f8d-4258-9852-253af591dcd5.png)
.eslintrc.js
![image](https://user-images.githubusercontent.com/8318475/130945610-9143068b-5d4c-4edc-9682-c371d6101b2b.png)

but there're none indentation inside <script> and <style> tags in Vue files. 
![image](https://user-images.githubusercontent.com/8318475/130946333-3b84b86b-2c2e-4b8f-baa5-5ac573432e96.png)
