### ISSUE TITLE
Consider making `eslint-config-prettier` optional dependency.

### ISSUE THREAD

**Issue by Astray-git** [meteorlxy/eslint-plugin-prettier-vue#14]
`eslint-config-prettier` is added here:
https://github.com/meteorlxy/eslint-plugin-prettier-vue/blob/ed8ddb683f42f4c987f7f239da1c564a361967e1/lib/configs.js#L6

When I have `SFCBlocks.script` disabled. I still want to use ESLint's format rules for script block.

**Comment by meteorlxy** [comment]
eslint-config-prettier is not in the dependencies list. The recommended config is not required, too. You can configure it yourself.
