### ISSUE TITLE
How can I change all error to warning?

### ISSUE THREAD

**Issue by ttpjb** [meteorlxy/eslint-plugin-prettier-vue#19]
![image](https://user-images.githubusercontent.com/20367534/124215446-36cf7700-db1e-11eb-8022-10a48392144f.png)
from red underlie to yellow underlie

**Comment by meteorlxy** [comment]
Set the rule `'prettier-vue/prettier'` to `'warning'`

https://github.com/meteorlxy/eslint-plugin-prettier-vue/blob/fff3b152eb653f137cfda001fd934e463481e083/src/configs.ts#L18-L20

**Comment by ttpjb** [comment]
Thank you for your answer. 
after I put your code, It works. but need to change from `warning` to `warn`
`rules: {
      'prettier-vue/prettier': 'warn',
    },`
