### ISSUE TITLE
Plugin hides actual ESLint rule involved

### ISSUE THREAD

**Issue by richardtallent** [meteorlxy/eslint-plugin-prettier-vue#21]
I keep banging my head against the wall on this. When I'm using this plugin and ESLint complains, it merely points to `eslint(prettier-vue/prettier`) rather than the actual ESLint rule involved. Example:

```Javascript
foo: function(row, col) {
```

returns this error:
```
Insert `·`eslint[prettier-vue/prettier](https://github.com/meteorlxy/eslint-plugin-prettier-vue#eslint-config)
```

The same URL is shown for every error.

Can we have the link to the offending rule instead?

**Comment by meteorlxy** [comment]
Sorry for delay.

In fact, the rule __is__ prettier itself.

You know that, prettier is an opinionated code formatter. It does not have a list of "rules" like ESLint. It just format your code with its own style.

Thus, when we use prettier as an ESLint plugin, the "prettier style" will perform as a "rule".
