### ISSUE TITLE
Possibility to transfer it nicely when using tailwindcss

### ISSUE THREAD

**Issue by vcharov** [meteorlxy/eslint-plugin-prettier-vue#30]
## Request / Idea
It would be nice to be able to transfer it nicely when using tailwindcss. This would make the code much more readable

## Input

```pug
header.header-module(
  class=["bg-off-white shadow-main-header flex items-center gap-x-2 py-2 px-4", "lg:px-8"]
)
```

## Expected Output

```pug
header.header-module(
  class=[
    "bg-off-white shadow-main-header flex items-center gap-x-2 py-2 px-4", 
    "lg:px-8"
  ]
)
```
![Снимок 2022-09-08 17 45 12](https://user-images.githubusercontent.com/107539028/189152793-c7dec2e2-b22d-4ef5-ab6c-02dee8b02321.png)

**Comment by meteorlxy** [comment]
Well, this is actually handled by prettier itself, and has nothing to do with this plugin.

I think it is influenced by the [printWidth](https://prettier.io/docs/en/options.html#print-width) in your prettier config.
